eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

##8765 - service-feign、8766 - service-feign2
server:
  port: 8080
spring:
  application:
    name: gateway
  redis:
    database:  0
    host: 127.0.0.1
    port: 6379
    #password:  # Redis服务器连接密码（默认为空）
    #timeout:  # 连接超时时间（毫秒）
