eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

##8765 - service-feign、8766 - service-feign2
server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
      gateway:
        routes:
          - id: get_route
            uri: lb://service-feign:8765,lb:ws://bullet:5678
            predicates:
            - Path=/api-a/**
            - Method=GET
            filters:
            - StripPrefix=1
            ## PostBosy为自定义的GatewayFilterFactory的名称除了GatewayFilterFactory的部分
            #- PostBosy=true
            ##熔断配置，当实际服务异常时调用
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback

          - id: feign_route
            uri: lb://service-feign:8765
            predicates:
            - Path=/api-a/**
            filters:
            - StripPrefix=1
            ##熔断配置，当实际服务异常时调用
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback

          - id: feign2_route
            uri: lb://service-feign2:8766
            predicates:
            - Path=/api-b/**
            filters:
            - StripPrefix=1
            ##熔断配置，当实际服务异常时调用
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback