eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080
spring:
  application:
    name: api-gateway
  redis:
    database:  0
    host: 127.0.0.1
    port: 6379
    #password:  # Redis服务器连接密码（默认为空）
    #timeout:  # 连接超时时间（毫秒）

##路由配置
zuul:
  routes:
    api-a:
      path: /api-admin/**
      serviceId: service-feign
    api-b:
      path: /api-b/**
      serviceId: service-feign2
